accounts/urls.py
from django.urls import path
from allauth.account.views import EmailVerificationSentView

from .views import (admin_dashboard,
                     mail_inbox, 
                     sent_mail, 
                     mail_draft, 
                     mail_compose,
                    instructor_application,
                    verify_application,
                    reject_application,
                    instructors_list,
                    instructor_profile,
                    rate_instructor,
                    ) 

app_name = 'account'

urlpatterns = [
    path('user/mail/inbox/', mail_inbox, name='mail_inbox'),
    path('user/mail/sent', sent_mail, name='sent_mail'),
    path('user/mail/drafts', mail_draft, name='mail_draft'),
    path('user/mail/compose', mail_compose, name='mail_compose'),
    path('user/admin/dashboard/', admin_dashboard, name='dashboard'),

    path('user/instructor/application/', instructor_application, name='instructor_application'),
    path('user/instructor/list/', instructors_list, name='instructors_list'),
    path('user/instructor/profile/<int:instructor_id>/', instructor_profile, name='instructor_profile'),
    path('user/instructor/rate/<int:instructor_id>/', rate_instructor, name='rate_instructor'),
    path('user/instructor/verify/<int:application_id>/', verify_application, name='verify_application'),
    path('user/instructor/reject/<int:application_id>/', reject_application, name='reject_application'),
]

daun/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('account/', include('accounts.urls', namespace='account')),
    path("", include("pages.urls", namespace='course')),
    path("students/", include("students.urls", namespace='student')),
    path('activity/', include('actstream.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (index, ManageCourseListView, CourseCreateView, CourseUpdateView, CourseDeleteView, 
                    course_detail, CourseModuleUpdateView, ContentCreateUpdateView, topic_detail, 
                    ContentDeleteView, CourseListView, course_unenroll, create_faculty, get_notifications, 
                    mark_notification_read, mark_all_notifications_read, create_assignment,
                    submit_assignment, assignment_detail, grade_assignments, get_submission_details, 
                    grade_submissions, create_assessment, manage_courses, attempt_assessment,
                    assessment_result, CourseCreateWizard, course_enroll)


app_name = 'course'

urlpatterns = [
    path('', index, name='index'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('coures/manage/', manage_courses, name='manage_courses'),

    path('faculty/create/', create_faculty, name='create_faculty'),
    path('home/', ManageCourseListView.as_view(), name='home'),
    path('course/create/', CourseCreateWizard.as_view(), name='course_create'),
    path('course/<slug:course_slug>/', course_detail, name='course'),
    path('courses/<slug:slug>/edit/', CourseUpdateView.as_view(), name='course_update'),
    path('courses/<slug:slug>/delete/',CourseDeleteView.as_view(), name='course_delete'),
    path('<slug:course_slug>/topic/manage', CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('topic/<int:topic_id>/content/<str:model_name>/create/', ContentCreateUpdateView.as_view(), name='topic_content_create'),
    path('topic/<int:topic_id>/content/<model_name>/<id>/', ContentCreateUpdateView.as_view(), name='topic_content_update'),
    path('topic/<int:topic_id>/view/', topic_detail, name='topic_detail'),
    path('content/<int:content_id>/delete', ContentDeleteView.as_view(), name='content_delete'),
    
    path('course/<slug:course_slug>/enroll/', course_enroll, name="enroll_course"),
    path('courses/<slug:course_slug>/unenroll/', course_unenroll, name='course_unenroll'),


    path('notifications/', get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/mark-read', mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', mark_all_notifications_read, name='mark_all_read'),

    path('course/<int:course_id>/assignment/create/', create_assignment, name='create_assignment'),
    path('course/<int:course_id>/topic/<int:topic_id>/assignment/<int:assignment_id>/submit', submit_assignment, name='submit_assignment'),
    path('assignment/<int:assignment_id>/topic/<int:topic_id>/course/<int:course_id>/detail', assignment_detail, name='assignment_detail'),
    path('students/assignments/grade', grade_assignments, name='grade_assignments'),
    path('course/students/assignments/<int:submission_id>/detail', get_submission_details, name='get_submission_details'),
    path('course/students/assignments/<int:submission_id>/grade', grade_submissions, name='grade_submissions'),

    path('course/<int:course_id>/assessment/create', create_assessment, name='create_assessment'),
    path('assessment/<int:assessment_id>/attempt/', attempt_assessment, name='attempt_assessment'),
    path('assessment/<int:attempt_id>/result/', assessment_result, name='assessment_result'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.urls import path
from .views import StudentHomePage, StudentCourseListView, manage_students, student_detail, bulk_student_actions

app_name = 'student'

urlpatterns = [
    path('student/home/', StudentHomePage.as_view(), name='student_home'),
    path('courses/<slug:faculty>/', StudentCourseListView.as_view(), name='student_courses_by_faculty'),
    path('manage_students/', manage_students, name='manage_students'),
    path('student/<int:student_id>/', student_detail, name='student_detail'),
    path('bulk_student_actions/', bulk_student_actions, name='bulk_student_actions'),
]

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>{% block title %}DjangoX{% endblock title %}</title>
  <meta name="description" content="A framework for launching new Django projects quickly.">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  {% block css %}
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'course:home' %}">DjangoX</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'course:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">About</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <div class="mr-auto">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Settings
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="#">{{ user.email }}</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
              </ul>
            </li>
          </ul>
        </div>
        {% else %}
        <div class="mr-auto">
          <form class="form d-flex">
            <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary ms-2">Sign up</a>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>

  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}
</body>

</html>

templates/mail_wrapper.html
<div class="email-menu-bar">
    <div class="compose-mail">
        <a href="{% url "account:mail_compose" %}" class="btn btn-block">Compose</a>
    </div>
    <div class="email-menu-bar-inner">
        <ul>
            <li class="active"><a href="mailbox.html"><i class="fa fa-envelope-o"></i>Inbox <span class="badge badge-success">8</span></a></li>
            <li><a href="{% url "account:sent_mail" %}"><i class="fa fa-send-o"></i>Sent</a></li>
            <li><a href="{% url "account:mail_draft" %}"><i class="fa fa-file-text-o"></i>Drafts <span class="badge badge-warning">8</span></a></li>
            <li><a href="mailbox.html"><i class="fa fa-cloud-upload"></i>Outbox <span class="badge badge-danger">8</span></a></li>
            <li><a href="mailbox.html"><i class="fa fa-trash-o"></i>Trash</a></li>
        </ul>
    </div>
</div>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Zemple{% endblock %}</title>
    <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon" />
    <!-- Use Font Awesome 5 CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/assets.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/components.css' %}">
    {% block extra_head %}
    {{ block.super }}
    <!-- Preloader styles moved to main.css -->
    {% endblock %}
</head>
<body>
<div id="preloader">
  <div class="preloader-spinner"></div>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm fixed-top" style="min-height:64px; z-index:1050;">
        <div class="container-fluid px-3 px-md-4">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'course:index' %}">
                <span class="font-weight-bold text-primary" style="font-size:1.3rem;">Zemple</span>
            </a>
            <!-- Top right icons inside navbar -->
            <div class="d-flex align-items-center ml-auto d-lg-none" style="height:100%;">
                <!-- Notifications button for mobile -->
                
                <div class="dropdown">
                    <button class="btn btn-link p-0 text-dark" type="button" id="mobileUserDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:1.7rem; line-height:1;">
                        <i class="fas fa-user-circle"></i>
                        <span class="sr-only">User menu</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right shadow animated-dropdown" aria-labelledby="mobileUserDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'account:dashboard' %}"><i class="fas fa-tachometer-alt mr-2"></i>Dashboard</a>
                            <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Profile</a>
                            <div class="dropdown-divider"></div>
                            <form action="{% url 'account_logout' %}" method="post" style="display:inline;">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit"><i class="fas fa-sign-out-alt mr-2"></i>Logout</button>
                            </form>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'account_login' %}">Log In</a>
                            <a class="dropdown-item" href="{% url 'account_signup' %}">Sign Up</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="navbar-nav mr-auto ml-lg-4 mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'course:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'course:course_list' %}">Courses</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Events</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url "account:dashboard" %}">Dashboard</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url "student:student_home" %}">My learning</a></li>
                </ul>
                <!-- Move user icons before search form for mobile -->
                <ul class="navbar-nav ml-auto align-items-center order-2 order-lg-3 mt-2 mt-lg-0 flex-row flex-nowrap d-none d-lg-flex">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown mx-2">
                            <a class="nav-link position-relative" href="#" id="notificationDropdown" role="button" 
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-lg"></i>
                                {% if unread_notifications %}
                                <span class="badge badge-danger position-absolute" 
                                    style="top:0;right:0;font-size:0.7rem;">
                                    {{ unread_notifications|length }}
                                </span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow" 
                                aria-labelledby="notificationDropdown"
                                style="min-width:300px;">
                                <!-- content remains same -->
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="avatar bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center" style="width:36px;height:36px;font-weight:600;font-size:1rem;">{{ request.user.username|slice:":1"|upper }}</span>
                                <span class="ml-2 d-none d-lg-inline">{{ request.user.get_full_name|default:request.user.username }}</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'account:dashboard' %}"><i class="fas fa-tachometer-alt mr-2"></i>Dashboard</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Profile</a>
                                <div class="dropdown-divider"></div>
                                <form action="{% url 'account_logout' %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button class="dropdown-item" type="submit"><i class="fas fa-sign-out-alt mr-2"></i>Logout</button>
                                </form>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item mx-2"><a class="btn btn-outline-primary px-4 w-100 mb-2 mb-lg-0" href="{% url 'account_login' %}">Log In</a></li>
                        <li class="nav-item"><a class="btn btn-primary px-4 w-100" href="{% url 'account_signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
                <!-- Responsive search form: show inline on desktop, collapse below on mobile -->
                <form class="form-inline my-2 my-lg-0 position-relative w-100 w-md-auto mx-lg-3 order-3 order-lg-2 d-none d-lg-flex" style="max-width:400px;">
                    <input class="form-control mr-sm-2 w-100" type="search" placeholder="Search for anything..." aria-label="Search">
                    <button class="btn btn-link position-absolute" type="submit" style="right:10px;top:50%;transform:translateY(-50%);color:#2563eb;"><i class="fas fa-search"></i></button>
                </form>
                <!-- Mobile search form: show only on mobile -->
                <form class="form-inline my-2 w-100 d-lg-none" style="max-width:100%; position:relative;">
                    <input class="form-control pr-5 w-100" type="search" placeholder="Search for anything..." aria-label="Search" style="padding-right:4.5rem;">
                    <button class="btn btn-link position-absolute" type="submit" style="right:0.5rem;top:50%;transform:translateY(-50%);color:#2563eb;padding:0 0.5rem;">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </nav>
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}{% endblock %}
{% include "footer.html" %}
<!-- Bottom Navigation Bar for Mobile -->
<nav class="bottom-nav d-lg-none">
    <a href="{% url 'course:index' %}" class="bottom-nav-item" title="Home">
        <i class="fas fa-home"></i>
    </a>
    <button class="bottom-nav-item" id="bottomNavSearchBtn" title="Search" type="button">
        <i class="fas fa-search"></i>
    </button>
    <a href="{% url 'course:course_list' %}" class="bottom-nav-item" title="Courses">
        <i class="fas fa-book"></i>
    </a>
    <a href="#" class="bottom-nav-item" title="Events">
        <i class="fas fa-calendar-alt"></i>
    </a>
    <a href="#" class="bottom-nav-item position-relative" title="Notifications">
        <i class="fas fa-bell"></i>
        {% if unread_notifications %}<span class="badge badge-danger position-absolute" style="top:2px;right:10px;font-size:0.7rem;">{{ unread_notifications|length }}</span>{% endif %}
    </a>
    <a href="#" class="bottom-nav-item" title="Settings">
        <i class="fas fa-cog"></i>
    </a>
</nav>
<!-- Mobile Search Overlay (hidden by default) -->
<div id="mobileSearchOverlay" class="mobile-search-overlay d-lg-none">
    <form class="mobile-search-form" autocomplete="off">
        <input class="form-control" type="search" placeholder="Search for anything..." aria-label="Search">
        <button class="btn btn-link" type="submit"><i class="fas fa-search"></i></button>
        <button class="btn btn-link close-search" type="button" id="closeMobileSearch"><i class="fas fa-times"></i></button>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script>
    // Preloader hide logic
    window.addEventListener('load', function() {
      var preloader = document.getElementById('preloader');
      if (preloader) {
        preloader.classList.add('hide');
        setTimeout(function() { preloader.style.display = 'none'; }, 600);
      }
    });
    // Navbar: collapse menu after clicking a nav link (on mobile)
    document.addEventListener('DOMContentLoaded', function() {
        var navLinks = document.querySelectorAll('.navbar-nav .nav-link');
        var navbarCollapse = document.getElementById('mainNavbar');
        navLinks.forEach(function(link) {
            link.addEventListener('click', function() {
                if (window.innerWidth < 992 && navbarCollapse.classList.contains('show')) {
                    $('.navbar-collapse').collapse('hide');
                }
            });
        });
        // Optional: close dropdown after clicking a dropdown item (mobile)
        var dropdownItems = document.querySelectorAll('.dropdown-menu .dropdown-item');
        dropdownItems.forEach(function(item) {
            item.addEventListener('click', function() {
                if (window.innerWidth < 992) {
                    $(this).closest('.dropdown-menu').dropdown('hide');
                }
            });
        });
    });
    // Animate dropdowns on show/hide
    $(function() {
        $('.dropdown').on('show.bs.dropdown', function () {
            var menu = $(this).find('.animated-dropdown');
            menu.addClass('show');
        });
        $('.dropdown').on('hide.bs.dropdown', function () {
            var menu = $(this).find('.animated-dropdown');
            menu.removeClass('show');
        });
    });
    // Mobile search overlay logic
    document.addEventListener('DOMContentLoaded', function() {
        var searchBtn = document.getElementById('bottomNavSearchBtn');
        var overlay = document.getElementById('mobileSearchOverlay');
        var closeBtn = document.getElementById('closeMobileSearch');
        if (searchBtn && overlay && closeBtn) {
            searchBtn.addEventListener('click', function() {
                overlay.classList.add('show');
                overlay.querySelector('input').focus();
            });
            closeBtn.addEventListener('click', function() {
                overlay.classList.remove('show');
            });
        }
    });
</script>
{% block extra_js %}{% endblock %}
</body>
</html>

templates/notifications.html
<div class="notification-dropdown">
    <button class="notification-bell">
        <i class="fas fa-bell"></i>
        {% if unread_notifications > 0 %}
        <span class="badge">{{ unread_notifications }}</span>
        {% endif %}
    </button>
    <div class="dropdown-content">
        {% for notification in recent_notifications %}
        <div class="notification-item {% if notification.is_read %}read{% endif %}" 
             data-notification-id="{{ notification.id }}">
            <div class="notification-header">
                <strong>{{ notification.title }}</strong>
                <small>{{ notification.created_at|timesince }} ago</small>
            </div>
            <p>{{ notification.message }}</p>
            {% if notification.related_course %}
            <a href="{% url 'course:course' notification.related_course.id %}" class="btn btn-sm">
                View Course
            </a>
            {% endif %}
        </div>
        {% empty %}
        <div class="notification-item">
            <p>No new notifications</p>
        </div>
        {% endfor %}
        <div class="notification-footer">
            <a href="{% url 'account:mail_inbox' %}">View All Notifications</a>
        </div>
    </div>
</div>

templates/reviews_partial.html
<!-- templates/reviews_partial.html -->
<div class="average-rating">
    <span class="display-4 font-weight-bold">{{ instructor.average_rating|floatformat:1 }}</span>
    <small>/5</small>
    <div class="stars">
        {% with ''|center:instructor.average_rating as range %}
            {% for _ in range %}
                <i class="fas fa-star text-warning"></i>
            {% endfor %}
        {% endwith %}
        {% if instructor.average_rating < 5 %}
            {% with ''|center:instructor.remaining_rating as range %}
                {% for _ in range %}
                    <i class="far fa-star text-warning"></i>
                {% endfor %}
            {% endwith %}
        {% endif %}
        <small class="text-muted ml-2">({{ ratings_received.count }} reviews)</small>
    </div>
</div>

<div class="review-list">
    {% for rating in ratings_received %}
    <div class="review-card">
        <!-- Your review card content -->
    </div>
    {% endfor %}
</div>

templates/sidebar.html
<div class="ttr-sidebar">
    <div class="ttr-sidebar-wrapper content-scroll">
        <!-- side menu logo start -->
        <div class="ttr-sidebar-logo">
            <a href="#"><img alt="" src="{% static "asset/images/logo.png" %}" width="122" height="27"></a>
            <!-- <div class="ttr-sidebar-pin-button" title="Pin/Unpin Menu">
                <i class="material-icons ttr-fixed-icon">gps_fixed</i>
                <i class="material-icons ttr-not-fixed-icon">gps_not_fixed</i>
            </div> -->
            <div class="ttr-sidebar-toggle-button">
                <i class="ti-arrow-left"></i>
            </div>
        </div>
        <!-- side menu logo end -->
        <!-- sidebar menu start -->
        <nav class="ttr-sidebar-navi">
            <ul>
                <li>
                    <a href="{% url "account:dashboard" %}" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-home"></i></span>
                        <span class="ttr-label">Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{% url "course:home" %}" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-book"></i></span>
                        <span class="ttr-label">Courses</span>
                    </a>
                </li>
                <li>
                    <a href="#" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-email"></i></span>
                        <span class="ttr-label">Mailbox</span>
                        <span class="ttr-arrow-icon"><i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul>
                        <li>
                            <a href="{% url "account:mail_inbox" %}" class="ttr-material-button"><span class="ttr-label">Mail Box</span></a>
                        </li>
                        <li>
                            <a href="mailbox-compose.html" class="ttr-material-button"><span class="ttr-label">Compose</span></a>
                        </li>
                        <li>
                            <a href="mailbox-read.html" class="ttr-material-button"><span class="ttr-label">Mail Read</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-calendar"></i></span>
                        <span class="ttr-label">Calendar</span>
                        <span class="ttr-arrow-icon"><i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul>
                        <li>
                            <a href="basic-calendar.html" class="ttr-material-button"><span class="ttr-label">Basic Calendar</span></a>
                        </li>
                        <li>
                            <a href="list-view-calendar.html" class="ttr-material-button"><span class="ttr-label">List View</span></a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-bookmark-alt"></i></span>
                        <span class="ttr-label">Bookmarks</span>
                    </a>
                </li>
                <li>
                    <a href="review.html" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-comments"></i></span>
                        <span class="ttr-label">Review</span>
                    </a>
                </li>
                <li>
                    <a href="add-listing.html" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-layout-accordion-list"></i></span>
                        <span class="ttr-label">Add listing</span>
                    </a>
                </li>
                <li>
                    <a href="#" class="ttr-material-button">
                        <span class="ttr-icon"><i class="ti-user"></i></span>
                        <span class="ttr-label">My Profile</span>
                        <span class="ttr-arrow-icon"><i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul>
                        <li>
                            <a href="user-profile.html" class="ttr-material-button"><span class="ttr-label">User Profile</span></a>
                        </li>
                        <li>
                            <a href="teacher-profile.html" class="ttr-material-button"><span class="ttr-label">Teacher Profile</span></a>
                        </li>
                    </ul>
                </li>
                <li class="ttr-seperate"></li>
            </ul>
            <!-- sidebar menu end -->
        </nav>
        <!-- sidebar menu end -->
    </div>
</div>