daun/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('account/', include('accounts.urls', namespace='account')),
    path("", include("pages.urls", namespace='course')),
    path("students/", include("students.urls", namespace='student')),
    path('activity/', include('actstream.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (index, ManageCourseListView, CourseCreateView, CourseUpdateView, CourseDeleteView, 
                    course_detail, CourseModuleUpdateView, ContentCreateUpdateView, topic_detail, 
                    ContentDeleteView, CourseListView, course_unenroll, create_faculty, get_notifications, 
                    mark_notification_read, mark_all_notifications_read, create_assignment,
                    submit_assignment, assignment_detail, grade_assignments, get_submission_details, 
                    grade_submissions, create_assessment, manage_courses, attempt_assessment,
                    assessment_result, CourseCreateWizard, course_enroll)


app_name = 'course'

urlpatterns = [
    path('', index, name='index'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('coures/manage/', manage_courses, name='manage_courses'),

    path('faculty/create/', create_faculty, name='create_faculty'),
    path('home/', ManageCourseListView.as_view(), name='home'),
    path('course/create/', CourseCreateWizard.as_view(), name='course_create'),
    path('course/<slug:course_slug>/', course_detail, name='course'),
    path('courses/<slug:slug>/edit/', CourseUpdateView.as_view(), name='course_update'),
    path('courses/<slug:slug>/delete/',CourseDeleteView.as_view(), name='course_delete'),
    path('<slug:course_slug>/topic/manage', CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('topic/<int:topic_id>/content/<str:model_name>/create/', ContentCreateUpdateView.as_view(), name='topic_content_create'),
    path('topic/<int:topic_id>/content/<model_name>/<id>/', ContentCreateUpdateView.as_view(), name='topic_content_update'),
    path('topic/<int:topic_id>/view/', topic_detail, name='topic_detail'),
    path('content/<int:content_id>/delete', ContentDeleteView.as_view(), name='content_delete'),
    
    path('course/<slug:course_slug>/enroll/', course_enroll, name="enroll_course"),
    path('courses/<slug:course_slug>/unenroll/', course_unenroll, name='course_unenroll'),


    path('notifications/', get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/mark-read', mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read/', mark_all_notifications_read, name='mark_all_read'),

    path('course/<int:course_id>/assignment/create/', create_assignment, name='create_assignment'),
    path('course/<int:course_id>/topic/<int:topic_id>/assignment/<int:assignment_id>/submit', submit_assignment, name='submit_assignment'),
    path('assignment/<int:assignment_id>/topic/<int:topic_id>/course/<int:course_id>/detail', assignment_detail, name='assignment_detail'),
    path('students/assignments/grade', grade_assignments, name='grade_assignments'),
    path('course/students/assignments/<int:submission_id>/detail', get_submission_details, name='get_submission_details'),
    path('course/students/assignments/<int:submission_id>/grade', grade_submissions, name='grade_submissions'),

    path('course/<int:course_id>/assessment/create', create_assessment, name='create_assessment'),
    path('assessment/<int:assessment_id>/attempt/', attempt_assessment, name='attempt_assessment'),
    path('assessment/<int:attempt_id>/result/', assessment_result, name='assessment_result'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse
from django.db.models import Avg
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .fields import OrderField

from accounts.models import CustomUser

User = get_user_model()
# Create your models here.

class Faculty(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'faculties'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name


class CourseManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True, is_active=True)

    
class Course(models.Model):
    class AudienceType(models.TextChoices):
        BEGINNER = 'beginner', _('Beginner')
        INTERMEDIATE = 'intermediate', _('Intermediate')
        ADVANCED = 'advanced', _('Advanced')
        ALL = 'all', _('All Levels')
    
    class PriceTier(models.TextChoices):
        FREE = 'free', _('Free')
        TIER_1000 = '1000', _('1,000')
        TIER_3000 = '3000', _('3,000')
        TIER_5000 = '5000', _('5,000')
        TIER_10000 = '10000', _('10,000')
        TIER_30000 = '30000', _('30,000')
        TIER_50000 = '50000', _('50,000')


    students = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment', related_name='courses_joined', blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='courses_created', on_delete=models.CASCADE)
    faculty = models.ForeignKey(Faculty, related_name='faculty_courses', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    code = models.CharField(max_length=6, null=True, blank=True)
    cover_image = models.ImageField(null=True, upload_to='courses/cover_images')
    overview = models.TextField()
    price_tier = models.CharField(max_length=20, choices=PriceTier.choices, default=PriceTier.FREE)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    created = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    audience = models.CharField(max_length=20, choices=AudienceType.choices, default=AudienceType.ALL)
    objects = CourseManager()
    all_objects = models.Manager()
    is_active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
    
    def get_absolute_url(self):
        return reverse('course:course', args=[self.slug])
        
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class CourseTrailer(models.Model):
    course = models.OneToOneField(Course, related_name='trailer', on_delete=models.CASCADE)
    video_url = models.URLField(null=True, blank=True)
    file = models.FileField(upload_to='course_trailers', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Course Trailers'
        ordering = ['course']

    def __str__(self):
        return f'Trailer for {self.course.name}'


class CourseRequirements(models.Model):
    course = models.ForeignKey(Course, related_name='requirements', on_delete=models.CASCADE)
    requirement = models.TextField()

    class Meta:
        verbose_name_plural = 'Course Requirements'
        ordering = ['course']

    def __str__(self):
        return f'Requirements for {self.course.name}'


class CourseObjectives(models.Model):
    course = models.ForeignKey(Course, related_name='objectives', on_delete=models.CASCADE)
    objective = models.TextField()

    class Meta:
        verbose_name_plural = 'Course Objectives'
        ordering = ['course']

    def __str__(self):
        return f'Objectives for {self.course.name}'

class Topic(models.Model):
    course = models.ForeignKey(Course, related_name='course_topics', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course'])
    is_completed = models.BooleanField(default=False)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}. {self.name}'


class Content(models.Model):
    topic = models.ForeignKey(Topic, related_name='contents', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={'model__in':('text','image','video','file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['topic'])

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_related', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
    
    def __str__(self):
        return self.title

class Text(ItemBase):
    content = models.TextField()

class File(ItemBase):
    file = models.FileField(upload_to='files')

class Image(ItemBase):
    file = models.FileField(upload_to='images')

class Video(ItemBase):
    url = models.URLField(null=True, blank=True)
    file = models.FileField(upload_to='videos', null=True, blank=True)

    def has_video(self):
        return bool(self.file or self.url)

class TaskType(models.TextChoices):
    QUIZ = 'quiz', 'Quiz'
    ASSIGNMENT = 'assignment', 'Assignment'
    ASSESSMENT = 'assessment', 'Assessment'
    EXAM = 'exam', 'Exam'
    PROJECT = 'project', 'Project'

class Task(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_tasks')
    start_date = models.DateTimeField()
    due_date = models.DateTimeField(null=True, blank=True)
    type = models.CharField(max_length=20, choices=TaskType.choices, default=TaskType.QUIZ)
    assignment = models.OneToOneField('Assignment', on_delete=models.CASCADE, related_name='assignment_task', null=True,blank=True)
    assessment = models.OneToOneField('Assessment', on_delete=models.CASCADE, related_name='assessment_task', null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return f'{self.title} - {self.course.name}'
    def save(self, *args, **kwargs):
        # Save the Task instance first to ensure it has a primary key
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

        # Now create UserTask objects for all students in the course
        students = self.course.students.all()
        existing_user_tasks = UserTask.objects.filter(task=self).values_list('user_id', flat=True)
        user_tasks = [
            UserTask(user=student, task=self) for student in students if student.id not in existing_user_tasks
        ]
        UserTask.objects.bulk_create(user_tasks)


class UserTask(models.Model):
    AssignmentStatus = (
        ('pending', 'Pending'),
        ('submitted', 'Submitted'),
        ('graded', 'Graded'),
        ('overdue', 'Overdue'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_tasks')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='user_tasks')
    is_completed = models.BooleanField(default=False)
    score = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=AssignmentStatus, default='pending')

    
    class Meta:
        ordering = ['is_completed' ,'task__due_date']


    def get_average_score(self):
        return UserTask.objects.filter(task=self.task).aggregate(Avg('score'))['score__avg']

    def get_gpa(self, user=None):
        if user is None:
            user = self.user
        graded_tasks = user.user_tasks.filter(score__isnull=False)

        if not graded_tasks.exists():
            return 0.0  # No GPA yet

        total_quality_points = 0
        total_units = 0

        for task_score in graded_tasks:
            score = task_score.score
            unit = 3  # assumed course unit

            if score >= 70:
                grade_point = 5
            elif score >= 60:
                grade_point = 4
            elif score >= 50:
                grade_point = 3
            elif score >= 45:
                grade_point = 2
            elif score >= 40:
                grade_point = 1
            else:
                grade_point = 0

            total_quality_points += grade_point * unit
            total_units += unit

        if total_units == 0:
            return 0.0

        return round(total_quality_points / total_units, 2)



    def __str__(self):
        return f'{self.user.username} - {self.task.title}'
    
class Enrollment(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='enrollments')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')

templates/components/alerts.html
<div class="edu-alert edu-alert-{{ type|default:'info' }} {% if dismissible %}alert-dismissible{% endif %}">
  <div class="edu-alert-content">
    {% if title %}<h4 class="edu-alert-title">{{ title }}</h4>{% endif %}
    <p class="edu-alert-message">{{ message }}</p>
  </div>
  
  {% if dismissible %}
  <button class="edu-alert-close" aria-label="Close">
    &times;
  </button>
  {% endif %}
</div>

templates/components/buttons.html
{% load static %}
<!-- Primary Button -->
<button class="btn-primary {% if extra_classes %}{{ extra_classes }}{% endif %}">
  {{ text }}
</button>

<!-- Secondary Button -->
<button class="btn-secondary {% if extra_classes %}{{ extra_classes }}{% endif %}">
  {{ text }}
</button>

<!-- Ghost Button -->
<button class="btn-ghost {% if extra_classes %}{{ extra_classes }}{% endif %}">
  {{ text }}
</button>

<!-- Loading State (Add to any button) -->
<span class="btn-loading">
  <svg class="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
  </svg>
</span>

templates/components/course_cards.html
<div class="course-card">
    <div class="course-card__header">
        <img src="{{ course.cover_image.url }}" alt="{{ course.name }}" class="course-card__image">
        <span class="course-card__badge">Bestseller</span>
        <button class="course-card__wishlist" aria-label="Add to wishlist">
            <i class="fas fa-heart"></i>
        </button>
    </div>
    
    <div class="course-card__body">
        <h3 class="course-card__title">
            <a href="{% url "course:course" course.slug %}"> {{ course.name|title }} </a>
          <span class="course-card__desc-tooltip">{{ course.overview|default_if_none:''|striptags }}</span>
        </h3>
        <div class="course-card__hoverbox">
          <h4>{{ course.name|title }}</h4>
          <div class="hoverbox-instructor">By {{ course.owner.full_name }}</div>
          <div class="hoverbox-desc">{{ course.overview|default_if_none:''|striptags }}</div>
          <div class="hoverbox-details">
            <span><i class="fas fa-clock"></i> 52 hours</span>
            <span><i class="fas fa-file-alt"></i> {{ course.course_topics.count }} topics</span>
          </div>
          <div class="hoverbox-meta">
            <span class="hoverbox-rating"><i class="fas fa-star"></i> 4.7</span>
            <span class="hoverbox-rating-count">(189,240)</span>
            <span class="hoverbox-price">${{ course.discount_price }}</span>
            <span class="hoverbox-original-price">${{ course.price_tier }}</span>
          </div>
        </div>
        <p class="course-card__instructor">{{ course.owner.full_name }}</p>
        
        <div class="course-card__meta">
            <div class="course-card__rating">
                <span class="course-card__stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                </span>
                <span class="course-card__rating-count">(189,240)</span>
            </div>
            
            <div class="course-card__pricing">
                <span class="course-card__price">₦{{ course.discount_price }}</span>
                <span class="course-card__original-price">₦{{ course.get_price_tier_display }}</span>
            </div>
        </div>
        
        <div class="course-card__details">
            <div class="course-card__detail-item">
                <i class="fas fa-clock"></i>
                <span>52 hours</span>
            </div>
            <div class="course-card__detail-item">
                <i class="fas fa-file-alt"></i>
                <span>{{ course.course_topics.count }} topics</span>
            </div>
        </div>
    </div>
    
    <div class="course-card__footer">
        <button class="course-card__cta">Add to Cart</button>
    </div>
</div>

templates/components/events_card.html
{% load static %}
<div class="event-card">
    <div class="event-card__header">
        <img src="{% static "asset/images/courses/pic2.jpg" %}" alt="Tech Conference 2024" class="event-card__image">
        <span class="event-card__status">Upcoming</span>
        <button class="event-card__save" aria-label="Save event">
            <i class="far fa-bookmark"></i>
        </button>
    </div>
    
    <div class="event-card__body">
        <div class="event-card__host">
            <img src="host-avatar.jpg" alt="Tech Events Inc" class="event-card__host-avatar">
            <span class="event-card__host-name">Tech Events Inc</span>
        </div>
        
        <h3 class="event-card__title" title="Tech conference on the future of technology and innovation. Join industry leaders and network with peers!">
           <a href="#"> Future Tech Summit 2024 </a>
          <span class="event-card__desc-tooltip">Tech conference on the future of technology and innovation. Join industry leaders and network with peers!</span>
        </h3>
        
        <div class="event-card__details">
            <div class="event-card__detail">
                <i class="fas fa-calendar-alt"></i>
                <div>
                    <span class="event-card__date">Fri, Oct 18, 2024</span>
                    <span class="event-card__time">10:00 AM - 6:00 PM CEST</span>
                </div>
            </div>
            
            <div class="event-card__detail">
                <i class="fas fa-map-marker-alt"></i>
                <div>
                    <span class="event-card__location-type">Virtual Event</span>
                    <span class="event-card__location">Online</span>
                </div>
            </div>
        </div>
        
        <div class="event-card__pricing">
            <span class="event-card__price">From $99</span>
            <span class="event-card__price-type">Early Bird</span>
        </div>
    </div>
    
    <div class="event-card__footer">
        <button class="event-card__cta">Register Now</button>
        <div class="event-card__attendees">
            <div class="event-card__avatars">
                <img src="user1.jpg" alt="Attendee">
                <img src="user2.jpg" alt="Attendee">
                <img src="user3.jpg" alt="Attendee">
            </div>
            <span class="event-card__attendee-count">500+ attending</span>
        </div>
    </div>
</div>

templates/components/forms.html
<!-- Input Field -->
<div class="form-group {% if errors %}has-error{% endif %}">
  {% if label %}
  <label for="{{ id }}" class="form-label">
    {{ label }}
    {% if required %}<span class="text-red-500">*</span>{% endif %}
  </label>
  {% endif %}
  
  <input
    type="{{ type|default:'text' }}"
    id="{{ id }}"
    name="{{ name }}"
    value="{{ value|default:'' }}"
    class="form-input {% if errors %}form-input-error{% endif %}"
    placeholder="{{ placeholder|default:'' }}"
    {% if required %}required{% endif %}
  >
  
  {% if help_text %}
  <p class="form-help-text">{{ help_text }}</p>
  {% endif %}
  
  {% if errors %}
  <ul class="form-error-list">
    {% for error in errors %}
    <li class="form-error-item">{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

<!-- Select Dropdown -->
<div class="form-group">
  <label for="{{ id }}" class="form-label">{{ label }}</label>
  <select class="form-select" id="{{ id }}" name="{{ name }}">
    {% for option in options %}
    <option value="{{ option.value }}" {% if option.selected %}selected{% endif %}>
      {{ option.label }}
    </option>
    {% endfor %}
  </select>
</div>

templates/components/navigation.html
<!-- Breadcrumbs -->
<nav class="edu-breadcrumbs">
  <ol class="flex items-center space-x-2">
    {% for item in items %}
    <li>
      {% if not forloop.last %}
      <a href="{{ item.url }}" class="edu-breadcrumb-link">{{ item.label }}</a>
      <span class="edu-breadcrumb-separator">/</span>
      {% else %}
      <span class="edu-breadcrumb-current">{{ item.label }}</span>
      {% endif %}
    </li>
    {% endfor %}
  </ol>
</nav>

<!-- Pagination -->
<div class="edu-pagination">
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}" class="edu-pagination-prev">
    Previous
  </a>
  {% endif %}
  
  <div class="edu-pagination-pages">
    {% for num in page.paginator.page_range %}
    <a href="?page={{ num }}" class="edu-pagination-page {% if num == page.number %}active{% endif %}">
      {{ num }}
    </a>
    {% endfor %}
  </div>
  
  {% if page.has_next %}
  <a href="?page={{ page.next_page_number }}" class="edu-pagination-next">
    Next
  </a>
  {% endif %}
</div>

templates/components/teach_on_zemple_banner.html
<div class="teach-on-zemple-banner">
  <div class="container d-flex flex-column flex-md-row align-items-center justify-content-between py-4">
    <div class="banner-content text-center text-md-start mb-3 mb-md-0">
      <h2 class="banner-title fw-bold mb-2">Teach on Zemple</h2>
      <p class="banner-subtitle mb-3">Share your knowledge, inspire students, and earn income. Join our community of expert instructors today!</p>
      <a href="/teach/" class="btn btn-primary btn-lg rounded-pill px-4 shadow-sm banner-cta">Start Teaching</a>
    </div>
    <div class="banner-illustration d-none d-md-block ms-md-4">
      <img src="/static/asset/teach-illustration.svg" alt="Teach on Zemple" class="img-fluid" style="max-height: 120px;">
    </div>
  </div>
</div>